name: ZthPreferences
version: '1.0-SNAPSHOT'
main: ink.magma.zthPreferences.ZthPreferences
api-version: '1.21'
authors: [ Magma ]
libraries:
  - 'redis.clients:jedis:5.2.0'

commands:
  pref:
    description: 管理个人偏好设置
    usage: /pref [show|toggle|help]
    permission: zthpreferences.use

permissions:
  zthpreferences.use:
    description: 允许使用偏好设置命令
    default: true
