name: ZthPreferences
version: '1.1.0'
main: ink.magma.zthPreferences.ZthPreferences
api-version: '1.21'
authors: [ Magma ]
libraries:
  - 'redis.clients:jedis:5.2.0'

commands:
  preferences:
    description: 管理个人偏好设置
    usage: /preferences [show|toggle|help|reload]
    permission: zth.preferences.use
    aliases: [prefs, pref, setting, settings, zthpreferences]
  drop:
    description: 调整丢弃物品开关，用于历史兼容
    usage: /drop
    permission: zth.preferences.use

permissions:
  zth.preferences.use:
    description: 允许使用偏好设置命令
    default: true
  zth.preferences.admin:
    description: "Allow to use admin commands."
    default: op
